import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import { ourFileRouter } from './api/uploadthing/core'
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Inventory',
  description: 'Generated by collinz dev',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Toaster
      position="top-center"
      reverseOrder={false}
      />
      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)}
        />
        <NavBar/>
        {children}
        </body>
    </html>
  )
}
